


name: Parse Issue to News JSON
on:
  issues:
    types: [opened, edited]

permissions:
  contents: write

jobs:
  parse-issue-to-news:
    runs-on: ubuntu-latest
    steps:
      - name: イベントトリガーチェック
        id: check_trigger
        run: |
          if [[ "${{ github.event.issue.body }}" == \#NEWS_EVENT* ]]; then
            echo "run_next=true" >> $GITHUB_OUTPUT
          else
            echo "run_next=false" >> $GITHUB_OUTPUT
          fi

      - name: チェックアウト
        if: steps.check_trigger.outputs.run_next == 'true'
        uses: actions/checkout@v4

      - name: Node.jsセットアップ
        if: steps.check_trigger.outputs.run_next == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Claude Code SDKセットアップ
        if: steps.check_trigger.outputs.run_next == 'true'
        run: |
          npm install -g @anthropic-ai/claude-code

      - name: パッケージインストールとスクリプト実行
        if: steps.check_trigger.outputs.run_next == 'true'
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          cd scripts
          npm install --legacy-peer-deps
          node parse-issue-to-news.js "$GITHUB_EVENT_PATH"

      - name: news.jsonの変更をコミット・プッシュ
        if: steps.check_trigger.outputs.run_next == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add public/news.json
          git commit -m "chore: news.json自動反映 [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

